### ISSUE TITLE
Lack of support for X-RateLimit during deployment

### ISSUE THREAD

**Issue by dziudek** [netlify/js-client#10]
Hi,

I have discovered an issue with your node client - your API has limit of 200 requests per minute, but it is impossible to handle it during deploying the website using your client.

I have temporary fixed this issue by limiting parallels connections from 20 to 2: https://github.com/netlify/node-client/blob/master/lib/deploy.js#L56

but in fact the library should handle the X-Rate* headers and detect API limitations during deploying a website automatically.

**Comment by bcomnes** [comment]
I've done some super large deploys with the new client and it seems to work alright.  Let me know if you run into issues with version 2.

**Comment by dziudek** [comment]
Hi @bcomnes ,

Thank you for the update - I will try to implement it in the next [Publii](https://github.com/getpublii/publii) release as we are currently using the old version :)
