### ISSUE TITLE
createSite not using arguments

### ISSUE THREAD

**Issue by elie222** [netlify/js-client#102]
I made a fix to the README about a related item which was just accepted:
https://github.com/netlify/js-client/pull/101

But now I realise it's not listening to any of the parameters I pass in. For example if I run:

```js
  const site = await client.createSite({
    name: `my-awesome-site`,
    repo: {
      provider: "github",
      ...
    },
  });
```

It doesn't name the site according to the name I provided (nor does any of the GitHub linking work)

**Comment by elie222** [comment]
I can confirm that using the REST API via Postman works fine for me and I can create a site with the name of my choosing.

**Comment by ehmicky** [comment]
It turns out the `README` was in fact correct, i.e. `createSite()` body should be in a `body` variable. I believe the correct call would be:

```js
const site = await client.createSite({
  body: {
    name: `my-awesome-site`,
    repo: {
      provider: "github",
      ...
    },
  }
});
```

**Comment by elie222** [comment]
Didn’t seem to work for me for some reason... the broken version did work but just didn’t listen to any of the arguments I passed it.

Could you provide a working example with body please

Best,
Eliezer

**Comment by ehmicky** [comment]
Hi @elie222, the example above should be a working example with body.

**Comment by elie222** [comment]
Ok strange. Didn’t work when I tried. Kept erroring. I ended up using the rest api directly to do what I needed and worked well.

Best,
Eliezer

**Comment by ehmicky** [comment]
Closing as stale, feel free to re-open if you're still experiencing this problem.
