### ISSUE TITLE
Ship a new release?

### ISSUE THREAD

**Issue by realityking** [netlify/js-client#11]
It'd would be nice to get #6 out into a release so npm stops telling me I'm using a deprecated version of `graceful-fs`.

**Comment by realityking** [comment]
@calavera Pretty please 😄

**Comment by b1f6c1c4** [comment]
@biilmann 17 months since the last version 😞

**Comment by realityking** [comment]
Looks like it got fixed with version 2.

**Comment by bcomnes** [comment]
We made it!
