### ISSUE TITLE
feat: parse error data

### ISSUE THREAD

**Issue by qm3ster** [netlify/js-client#12]
Currently, unsuccessful requests `.reject` the promise with a strange `{ client, data, meta }` object.

1. Why is client in there?
2. Why is data an unparsed string of this kind:
```js
{ data: '{"code":429,"message":"API Deploy rate limit surpassed for application"}' }
{ data: '{"errors":{"subdomain":["must be unique"]}}' }
```
Maybe it would be better to reject with an `Error` object containing the message part and the other things like meta, code, and errors tacked on as properties?

**Comment by bcomnes** [comment]
Version two should have better error handling.  Check it out!
