### ISSUE TITLE
Chore: delete `src/addons.js` from the codebase

### ISSUE THREAD

**Issue by erezrokah** [netlify/js-client#173]
Per https://github.com/netlify/cli/issues/310 we should delete https://github.com/netlify/js-client/blob/2b90af2dcae5556c8f0b61f7c6ec9fbd895235b6/src/addons.js once https://github.com/netlify/cli/pull/1344 is merge.

**Comment by ehmicky** [comment]
This would be great, as it would make this client thinner.
Note: removing those endpoints is not a breaking change since those are not exported by the `main` entry file.

**Comment by erezrokah** [comment]
That file is still used in our large media plugin:
https://github.com/netlify/netlify-lm-plugin/blob/e177e391c27f4ce6672efa123780e47d724fcda3/src/commands/lm/setup.ts#L7
We should able to remove it once https://github.com/netlify/cli/pull/1489 is published
