### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by realityking** [netlify/js-client#24]
The Readme states that the library supports both Node.js and the browser. Looking for the browser code I only found

https://github.com/netlify/js-client/blob/029fc09a9273f36731eb89b678fbcce1a4ac5204/src/deploy/index.browser.js#L4

Is browser support planned for the future or is the readme wrong?

**Comment by realityking** [comment]
Nevermind - I misunderstood what that file is for.

**Comment by bcomnes** [comment]
Browser support is supre rudimentary still.  Milage may vary! Once the CLI is fully released I hope to circle back and add some simple tests to confirm thins like site / deploy retreval.
