### ISSUE TITLE
Build settings environment variables are not getting updated

### ISSUE THREAD

**Issue by matusferko** [netlify/js-client#429]
Hi, I am trying createSite() or updateSite() of your js API. 
I can create (partially) new site with createSite. The name of the new site is correct but no other arguments are taken into account .
I am actually just trying to populate environment variables in build settings with 
```
.updateSite({
    site_id,
    build_settings: {env}
  });
}

```
But nothing gets updated

**Comment by ehmicky** [comment]
Hi @matusferko,

Does the following work instead?

```js
api.updateSite({
    site_id,
    body: { build_settings: {env} }
  });
}
```

**Comment by matusferko** [comment]
omg that worked. Thanks @ehmicky 
What get's updated on update? Are all the settings overwritten or only properties which are defined?

**Comment by ehmicky** [comment]
Great! :tada: 

To answer your question: only the properties which are defined.
