### ISSUE TITLE
Create new site (and delete existing one)

### ISSUE THREAD

**Issue by AlenPelin** [netlify/js-client#43]
We are trying to create new site on netlify and deploy files as a one command. While deploy command is available in the client, create site functionality is missing, as well as removing site. Considering these functions are available in C# client, it looks natural to have them here.

**Comment by bcomnes** [comment]
Every open-api defined in our spec is available in this client.  The `createSite` method should be available and operational on an authenticated client: https://open-api.netlify.com/#/default/createSite

The methods of this client are dynamically generated from that spec, and aren't explicitly listed in the README, although maybe it would be worthwhile to also generate those in the README somehow.

It is expected that one refers to the open-api operation ID's listed in the right hand side of the open-api website to discover all available methods: https://open-api.netlify.com

Closing, but please let me know if there is any other outstanding issue we need to discuss, and apologies for the confusion!

**Comment by bcomnes** [comment]
See https://github.com/netlify/js-client#open-api-client-methods for our existing documentation on this functionality.

**Comment by AlenPelin** [comment]
Thanks @bcomnes for clarification.
