### ISSUE TITLE
Functions do not deploy when following README

### ISSUE THREAD

**Issue by rickh94** [netlify/js-client#55]
**- What is the current behavior?**
Functions do not deploy to Netlify when a functions directory is specified as `functionsDir` in `opts` object of `client.deploy()`, as described in the API Flow methods section of  README.md, and instead are silently skipped. Functions do deploy when a function directory is specified as `fnDir`, matching implementation in `src/deploy/index.js`.

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Attempt to deploy functions using `client.deploy('SOME_SITE_ID', './dist', { functionsDir: './functions' }` as in README.md. Functions do not deploy. 
1. Change to `client.deploy('SOME_SITE_ID', './dist', { fnDir: './functions' }`. Functions deploy correctly.

**- What is the expected behavior?**
Opts for `client.deploy` match in README and functionality.

**- Please mention your node.js, and operating system version.**
Node v8.11.0
Ubuntu 19.04/disco

**Comment by bcomnes** [comment]
This looks like a typo.
