### ISSUE TITLE
Typescript build giving Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by MatthewPardini** [netlify/js-client#693]
**- Do you want to request a _feature_ or report a _bug_?**
  Bug

**- What is the current behavior?**
  When importing the default from 'netlify' in a typescript app, I get the following error:

```
/my-app/dist/graphql/resolvers/Mutations/site.js:7
const netlify_1 = __importDefault(require("netlify"));
                                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /my-app/node_modules/netlify/src/index.js from /my-app/dist/graphql/resolvers/Mutations/site.js not supported.
Instead change the require of index.js in /my-app/dist/graphql/resolvers/Mutations/site.js to a dynamic import() which is available in all CommonJS modules.
```

**- If the current behavior is a bug, please provide the steps to reproduce.**

set up a typescript node project with the following ts config:
```
{
  "compilerOptions": {
    "target": "ES2021",
    "module": "commonjs",
    "lib": [
      "esnext"
    ],
    "moduleResolution": "node",
    "strict": true,
    "rootDir": "src",
    "outDir": "dist",
    "sourceMap": true,
    "esModuleInterop": true,
    "types": ["jest"]
  }
}
```

Add netlify to a declaration file, desc.d.ts:
```
declare module 'netlify'
```

Import netlify into a module for usage:
```
import NetlifyApi from 'netlify'

const api = new NetlifyAPI(NETLIFY_TOKEN)

const site = await api.createSite({
  account_slug: "myAccount",
  body: {
    name: "a-new-site",
    repo: {
      provider: "bitbucket",
      repo: "myRepos/myRepo",
      private: true,
      branch: "master",
    },
  } 
})
```

Then run `tsc` and serve the output.

**- What is the expected behavior?**
Compiled code should work with commonjs modules and es2021 targeted.

**- Please mention your node.js, and operating system version.**
node 16.14.0, macOs 11.6.4

**Comment by ehmicky** [comment]
Hi @MatthewPardini,

This package is a pure ES module, which requires you code to also use pure ES modules. In TypeScript, [this means using `nodenext`](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#esm-nodejs). Alternatively, if you have issues switching to pure ES modules, you can use a dynamic import:

```js
const NetlifyApi = await import('netlify') 
```

More information can also be [found here](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

**Comment by MatthewPardini** [comment]
Using nodenext on the nightly builds 1) isn't stable and 2) doesn't work with several other packages. So that isn't a solution. I can do dynamic imports for now but i'd rather not. Will wait for typescript to catch up to netlify.

Kind of a headscratcher that this package is distributed in esm since its main usage is in node which is friendlier to cjs.

**Comment by MatthewPardini** [comment]
Dynamic import allows for compilation but errors at run time (when the import is called) with an identical error. Neither of these are solutions that work

**Comment by mariobalca** [comment]
> Dynamic import allows for compilation but errors at run time (when the import is called) with an identical error. Neither of these are solutions that work

Same happening thing happening here (also Typescript).
Did you find any solution?

**Comment by MatthewPardini** [comment]
I didn’t use the client and just called the api myself

**Comment by mariobalca** [comment]
I see, and you probably had to use OAuth to authenticate requests right?
I was hoping I could use the API key that I've generated

**Comment by MatthewPardini** [comment]
I used the api key, not oauth. I am only hitting netlify on an account that I own from services I own so there is no need for oauth

**Comment by mariobalca** [comment]
You're right! Also got it to work

If anyone else in the future might be interested, here's a snippet:

```javascript
const netlifyClient = Axios.create({
    baseURL: 'https://api.netlify.com/api/v1/',
    headers: {
        Authorization: `Bearer ${getConfig().NETLIFY_API_KEY}`
    }
})
const { data: netlifySites } = await netlifyClient.get('sites')
```
