### ISSUE TITLE
createSiteBuild

### ISSUE THREAD

**Issue by atrimn** [netlify/js-client#77]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
Error: Missing required param site_id

**- If the current behavior is a bug, please provide the steps to reproduce.**
`          const build = await currentClient.createSiteBuild({
            body: {
              site_id: deploy.site_id
            }
          })`

**- What is the expected behavior?**
to create the build
**- Please mention your node.js, and operating system version.**
node v10.16.0 macOS catalina 10.15.2

**Comment by DavidWells** [comment]
Hey @atrimn 

Can you try:

```js
const build = await currentClient.createSiteBuild({ site_id: deploy.site_id })
```

IIRC the params get mapped to the body automatically

**Comment by atrimn** [comment]
> Hey @atrimn
> 
> Can you try:
> 
> ```js
> const build = await currentClient.createSiteBuild({ site_id: deploy.site_id })
> ```
> 
> IIRC the params get mapped to the body automatically

I tried that just tried again 
`        const build = await currentClient.createSiteBuild({
          site_id: deploy.site_id
        })`

got this response
Error: Missing required param site_id

**Comment by ehmicky** [comment]
@atrimn, thanks for reaching out.

Could you please include the stack trace?
Also could you confirm `deploy.site_id` is not `undefined`, `null` or an empty string?
Thanks a lot.

**Comment by atrimn** [comment]
> @atrimn, thanks for reaching out.
> 
> Could you please include the stack trace?
`Trace: Error: Missing required param site_id
    at Object.values.forEach.param (/Users/adrianlineweaver/Desktop/netlifyStealthist/node_modules/netlify/src/open-api/index.js:34:15)
    at Array.forEach (<anonymous>)
    at NetlifyAPI.createSiteBuild (/Users/adrianlineweaver/Desktop/netlifyStealthist/node_modules/netlify/src/open-api/index.js:28:43)
    at download (/Users/adrianlineweaver/Desktop/netlifyStealthist/index.js:62:45)
    at download (/Users/adrianlineweaver/Desktop/netlifyStealthist/index.js:68:19)`
> Also could you confirm `deploy.site_id` is not `undefined`, `null` or an empty string?
`{ deployId: '5dceafe6907625c10a4b2f5e',
  deploy:
   { id: '5dceafe6907625c10a4b2f5e',
     site_id: '15aa7ec3-83b5-4936-a1be-2465a43e222f',
     build_id: null,
     state: 'ready',
     name: 'my-awesome-site',
     url: 'http://my-awesome-site.netlify.com',
     ssl_url: 'https://my-awesome-site.netlify.com',
     admin_url: 'https://app.netlify.com/sites/my-awesome-site',
     deploy_url:
      'http://5dceafe6907625c10a4b2f5e.my-awesome-site.netlify.com',
     deploy_ssl_url:
      'https://5dceafe6907625c10a4b2f5e--my-awesome-site.netlify.com',
     created_at: '2019-11-15T14:02:14.348Z',
     updated_at: '2019-11-15T14:02:14.710Z',
     user_id: '5cf6cb46c810a0266bae9070',
     error_message: null,
     required: [],
     required_functions: [],
     commit_ref: null,
     review_id: null,
     branch: null,
     commit_url: null,
     skipped: null,
     locked: null,
     log_access_attributes:
      { type: 'firebase',
        url:
         'https://netlify-builds2.firebaseio.com/deploys/5dceafe6907625c10a4b2f5e/log',
        endpoint: 'https://netlify-builds2.firebaseio.com',
        path: '/deploys/5dceafe6907625c10a4b2f5e/log',
        token: '0VPdBEVIpCELfwkwswXemwtSydJqaDDZxZZhN9fV' },
     title: null,
     review_url: null,
     published_at: '2019-11-15T14:02:14.506Z',
     context: 'production',
     deploy_time: 0,
     available_functions: [],
     summary: { status: 'ready', messages: [Array] },
     screenshot_url: null,
     site_capabilities:
      { title: 'Netlify Team Free',
        asset_acceleration: true,
        form_processing: true,
        cdn_propagation: 'partial',
        build_gc_exchange: 'buildbot-gc',
        build_node_pool: 'buildbot-external-ssd',
        domain_aliases: true,
        secure_site: false,
        prerendering: true,
        proxying: true,
        ssl: 'custom',
        rate_cents: 0,
        yearly_rate_cents: 0,
        cdn_network: 'free_cdn_network',
        ipv6_domain: 'cdn.makerloop.com',
        branch_deploy: true,
        managed_dns: true,
        geo_ip: true,
        split_testing: true,
        id: 'nf_team_dev' },
     committer: null,
     skipped_log: null },
  uploadList: [] }`
> Finally, which version of the `js-client` are you using?
`    "netlify": "^2.4.8",`
> Thanks a lot.

Thanks for taking a look

**Comment by atrimn** [comment]
It was an error on my end deploy.site_id was undefined.
deploy.deploy.site_id was the correct way of accessing the property.

**Comment by ehmicky** [comment]
Thanks for letting us know. Glad this works for you now.
