### ISSUE TITLE
[DX] Return better error messages on failed API requests

### ISSUE THREAD

**Issue by DavidWells** [netlify/js-client#84]
When a fetch request happens to the API and something goes wrong the typical error thrown is:

```
FetchError: invalid json response body at https://api.netlify.com/api/v1/xyz reason: Unexpected end of JSON input
```

Ref: https://github.com/netlify/cli/issues/622

Instead, we should give an actionable error message to the user.

**Comment by ehmicky** [comment]
Thanks for reporting this bug. This should be fixed with #85.
