### ISSUE TITLE
Do not expose API token

### ISSUE THREAD

**Issue by ehmicky** [netlify/js-client#86]
The API token is exposed as `apiClient.accessToken`. This is a security concern when the client is passed between different trusted domains.

For example, Build plugins perform logic on behalf of the user. They receive an instance of the API client with the user's access token. However they should not see the API token.

**Comment by erquhart** [comment]
@rybit I remember hearing the access token we're receiving is stripped down to avoid this security concern, can you confirm?

**Comment by rybit** [comment]
There are two tokens here:
- one is the build one, this is exposed only to the buildbot and passed into the API in some cases
- one is a fuller token, this is stripped down for PRs and forks. There is ongoing work to not expose this on the backend or only in certain cases

**Comment by ehmicky** [comment]
Note: we are currently relying on this for https://github.com/netlify/edge-functions-deploy-plugin, but this is a temporary workaround.

**Comment by ehmicky** [comment]
Closing in favor of https://github.com/netlify/build/issues/1316 and https://github.com/netlify/buildbot/issues/756.

This is not a security concern anymore since the API token has restricted capabilities.
