### ISSUE TITLE
Add Typescript types to package or @types/netlify

### ISSUE THREAD

**Issue by South-Paw** [netlify/js-client#89]
**- Do you want to request a *feature* or report a *bug*?**

Feature I guess?

**- What is the current behavior?**

There are no Typescript types in the repo or on `@types/netlify` for this package

**- What is the expected behavior?**

There are types for the package 😄 

**- Please mention your node.js, and operating system version.**

n/a

**Comment by imranmomin** [comment]
Duplicate https://github.com/netlify/js-client/issues/50

**Comment by ehmicky** [comment]
You're right @imranmomin. Closing this in favor of #50.

**Comment by South-Paw** [comment]
@imranmomin @ehmicky apologies, I did search to see if someone else had raised something but didn't see #50 😞

**Comment by ehmicky** [comment]
No worries! This happens to me all the time :)
