### ISSUE TITLE
How do you handle error responses?

### ISSUE THREAD

**Issue by cyboolo** [netlify/js-client#9]
Hi

How do you handle error responses with netlify node-client.

For instance, if I update a site with a name that is already taken, how do you get the error response from update call.

I tried
`client.site(req.params.b).then(function(site) {
		
  		site.update({name: req.params.c}).then(function(site) {
  		res.success(site);
		}, function(error){
		res.error(error);	
		});
	});`

But it does not work.

Any help please

**Comment by bcomnes** [comment]
Version 2 should have better error handling.  You can check the cli for various ways to handle errors https://github.com/netlify/cli

If you have specific methods that you need help with let me know.
